package com.toolq.qq.protocol.jce.friend;

import com.qq.taf.jce.JceInputStream;
import com.qq.taf.jce.JceStruct;

public class FriendInfo extends JceStruct {
    static int cache_eIconType = 0;
    static int cache_eNetworkType = 0;
    static VipBaseInfo cache_oVipInfo = new VipBaseInfo();
    static byte[] cache_vecCardID = new byte[1];
    static byte[] cache_vecExtOnlineBusinessInfo = new byte[1];
    static byte[] cache_vecExtSnsFrdData = new byte[1];
    static byte[] cache_vecIMGroupID = new byte[1];
    static byte[] cache_vecIntimateInfo = new byte[1];
    static byte[] cache_vecMSFGroupID = new byte[1];
    static byte[] cache_vecMusicInfo = new byte[1];
    static byte[] cache_vecMutualMarkData = new byte[1];
    static byte[] cache_vecPoiInfo = new byte[1];
    static byte[] cache_vecRing = new byte[1];
    public byte cApolloFlag;
    public byte cCentiShow3DFlag;
    public byte cKingOfGloryFlag;
    public byte cNetwork;
    public byte cNewLoverDiamondFlag;
    public byte cOlympicTorch;
    public byte cSex;
    public byte cShowNameplate;
    public byte cSpecialFlag;
    public byte detalStatusFlag;
    public int eIconType = 0;
    public int eNetworkType = 0;
    public short faceId;
    public long friendUin;
    public byte groupId;
    public int iBatteryStatus;
    public int iTermType;
    public byte isIphoneOnline;
    public byte isMqqOnLine;
    public byte isRemark;
    public byte memberLevel;
    public String nick = "";
    public VipBaseInfo oVipInfo;
    public String remark = "";
    public String sDOVId = "";
    public String sShowName = "";
    public byte sqqOnLineState;
    public byte sqqOnLineStateV2;
    public byte sqqtype;
    public byte status = 20;
    public String strEimId = "";
    public String strEimMobile = "";
    public String strMasterUin = "";
    public String strTermDesc = "";
    public long uAbiFlag;
    public long uApolloSignTime;
    public long uApolloTimestamp;
    public long uBothFlag;
    public long uColorRing;
    public long uExtOnlineStatus;
    public long uFaceStoreId;
    public long uFontEffect;
    public long uFounderFont;
    public long uGameAppid;
    public long uGameLastLoginTime;
    public long uLastMedalUpdateTime;
    public long uLaviUin;
    public long uTagUpdateTime;
    public long uVipFont;
    public long ulBitSet;
    public long ulFaceAddonId;
    public long ulKingOfGloryRank;
    public byte[] vecCardID;
    public byte[] vecExtOnlineBusinessInfo;
    public byte[] vecExtSnsFrdData;
    public byte[] vecIMGroupID;
    public byte[] vecIntimateInfo;
    public byte[] vecMSFGroupID;
    public byte[] vecMusicInfo;
    public byte[] vecMutualMarkData;
    public byte[] vecPoiInfo;
    public byte[] vecRing;

    @Override
    public void readFrom(JceInputStream jceInputStream) {
        this.friendUin = jceInputStream.read(this.friendUin, 0, true);
        this.groupId = jceInputStream.read(this.groupId, 1, true);
        this.faceId = jceInputStream.read(this.faceId, 2, true);
        this.remark = jceInputStream.readString(3, true);
        this.sqqtype = jceInputStream.read(this.sqqtype, 4, true);
        this.status = jceInputStream.read(this.status, 5, true);
        this.memberLevel = jceInputStream.read(this.memberLevel, 6, false);
        this.isMqqOnLine = jceInputStream.read(this.isMqqOnLine, 7, false);
        this.sqqOnLineState = jceInputStream.read(this.sqqOnLineState, 8, false);
        this.isIphoneOnline = jceInputStream.read(this.isIphoneOnline, 9, false);
        this.detalStatusFlag = jceInputStream.read(this.detalStatusFlag, 10, false);
        this.sqqOnLineStateV2 = jceInputStream.read(this.sqqOnLineStateV2, 11, false);
        this.sShowName = jceInputStream.readString(12, false);
        this.isRemark = jceInputStream.read(this.isRemark, 13, false);
        this.nick = jceInputStream.readString(14, false);
        this.cSpecialFlag = jceInputStream.read(this.cSpecialFlag, 15, false);
        this.vecIMGroupID = jceInputStream.read(cache_vecIMGroupID, 16, false);
        this.vecMSFGroupID = jceInputStream.read(cache_vecMSFGroupID, 17, false);
        this.iTermType = jceInputStream.read(this.iTermType, 18, false);
        this.oVipInfo = (VipBaseInfo) jceInputStream.read(cache_oVipInfo, 19, false);
        this.cNetwork = jceInputStream.read(this.cNetwork, 20, false);
        this.vecRing = jceInputStream.read(cache_vecRing, 21, false);
        this.uAbiFlag = jceInputStream.read(this.uAbiFlag, 22, false);
        this.ulFaceAddonId = jceInputStream.read(this.ulFaceAddonId, 23, false);
        this.eNetworkType = jceInputStream.read(this.eNetworkType, 24, false);
        this.uVipFont = jceInputStream.read(this.uVipFont, 25, false);
        this.eIconType = jceInputStream.read(this.eIconType, 26, false);
        this.strTermDesc = jceInputStream.readString(27, false);
        this.uColorRing = jceInputStream.read(this.uColorRing, 28, false);
        this.cApolloFlag = jceInputStream.read(this.cApolloFlag, 29, false);
        this.uApolloTimestamp = jceInputStream.read(this.uApolloTimestamp, 30, false);
        this.cSex = jceInputStream.read(this.cSex, 31, false);
        this.uFounderFont = jceInputStream.read(this.uFounderFont, 32, false);
        this.strEimId = jceInputStream.readString(33, false);
        this.strEimMobile = jceInputStream.readString(34, false);
        this.cOlympicTorch = jceInputStream.read(this.cOlympicTorch, 35, false);
        this.uApolloSignTime = jceInputStream.read(this.uApolloSignTime, 36, false);
        this.uLaviUin = jceInputStream.read(this.uLaviUin, 37, false);
        this.uTagUpdateTime = jceInputStream.read(this.uTagUpdateTime, 38, false);
        this.uGameLastLoginTime = jceInputStream.read(this.uGameLastLoginTime, 39, false);
        this.uGameAppid = jceInputStream.read(this.uGameAppid, 40, false);
        this.vecCardID = jceInputStream.read(cache_vecCardID, 41, false);
        this.ulBitSet = jceInputStream.read(this.ulBitSet, 42, false);
        this.cKingOfGloryFlag = jceInputStream.read(this.cKingOfGloryFlag, 43, false);
        this.ulKingOfGloryRank = jceInputStream.read(this.ulKingOfGloryRank, 44, false);
        this.strMasterUin = jceInputStream.readString(45, false);
        this.uLastMedalUpdateTime = jceInputStream.read(this.uLastMedalUpdateTime, 46, false);
        this.uFaceStoreId = jceInputStream.read(this.uFaceStoreId, 47, false);
        this.uFontEffect = jceInputStream.read(this.uFontEffect, 48, false);
        this.sDOVId = jceInputStream.readString(49, false);
        this.uBothFlag = jceInputStream.read(this.uBothFlag, 50, false);
        this.cCentiShow3DFlag = jceInputStream.read(this.cCentiShow3DFlag, 51, false);
        this.vecIntimateInfo = jceInputStream.read(cache_vecIntimateInfo, 52, false);
        this.cShowNameplate = jceInputStream.read(this.cShowNameplate, 53, false);
        this.cNewLoverDiamondFlag = jceInputStream.read(this.cNewLoverDiamondFlag, 54, false);
        this.vecExtSnsFrdData = jceInputStream.read(cache_vecExtSnsFrdData, 55, false);
        this.vecMutualMarkData = jceInputStream.read(cache_vecMutualMarkData, 56, false);
        this.uExtOnlineStatus = jceInputStream.read(this.uExtOnlineStatus, 57, false);
        this.iBatteryStatus = jceInputStream.read(this.iBatteryStatus, 58, false);
        this.vecMusicInfo = jceInputStream.read(cache_vecMusicInfo, 59, false);
        this.vecPoiInfo = jceInputStream.read(cache_vecPoiInfo, 60, false);
        this.vecExtOnlineBusinessInfo = jceInputStream.read(cache_vecExtOnlineBusinessInfo, 61, false);
    }
    
    static {
        cache_vecIMGroupID[0] = 0;
        cache_vecMSFGroupID[0] = 0;
        cache_vecRing[0] = 0;
        cache_vecCardID[0] = 0;
        cache_vecIntimateInfo[0] = 0;
        cache_vecExtSnsFrdData[0] = 0;
        cache_vecMutualMarkData[0] = 0;
        cache_vecMusicInfo[0] = 0;
        cache_vecPoiInfo[0] = 0;
        cache_vecExtOnlineBusinessInfo[0] = 0;
    }
}

